name: Build wheels

on:
  push:

jobs:
  build-wheel-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: python
        uses: actions/setup-python@v4
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2

      - name: setup xcode version
        if: startsWith(matrix.os, 'macos')
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11'
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
